name: 'Publish BlazorApp'
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # Checkout the code
        - uses: actions/checkout@v2

        # Install .NET Core SDK
        - name: Setup .NET Core
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 6.x

        # Run tests Testプロジェクトがない場合はコメントアウトが必要
        - name: Test
          run: dotnet test GithubPages/GithubPages.csproj

        # Generate the website
        - name: Publish
          run: dotnet publish GithubPages/GithubPages.csproj --configuration Release

        # Publish the website
        - name: Deploy Github Pages
          uses: peaceiris/actions-gh-pages@v3.6.1
          with:
            github_token: ${{ secrets.TOKEN }} #Secretに登録したTokenを設定
            publish_branch: gh-pages
            publish_dir: bin/Release/net6.0/publish/wwwroot
            allow_empty_commit: false
            keep_files: false
            force_orphan: true
